name: Weekly SMC Alert Bot

on:
  schedule:
    - cron: "0 16 * * 5"  # Every Friday at 9:30 PM IST (4 PM UTC)
  workflow_dispatch:

jobs:
  run-signal-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python smc_weekly_scanner.py
